# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateKeyDialog.ui'
#
# Created: Sun May 24 16:09:45 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CreateKeyDialog(object):
    def setupUi(self, CreateKeyDialog):
        CreateKeyDialog.setObjectName(_fromUtf8("CreateKeyDialog"))
        CreateKeyDialog.resize(379, 305)
        icon = QtGui.QIcon()
        icon.addFile(_fromUtf8(":/images/register32.png"))
        CreateKeyDialog.setWindowIcon(icon)
        self.vboxlayout = QtGui.QVBoxLayout(CreateKeyDialog)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.stack = QtGui.QStackedWidget(CreateKeyDialog)
        self.stack.setObjectName(_fromUtf8("stack"))
        self.inputPage = QtGui.QWidget()
        self.inputPage.setObjectName(_fromUtf8("inputPage"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.inputPage)
        self.vboxlayout1.setMargin(9)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.label = QtGui.QLabel(self.inputPage)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.vboxlayout1.addWidget(self.label)
        self.groupBox = QtGui.QGroupBox(self.inputPage)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridlayout = QtGui.QGridLayout(self.groupBox)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.password2 = QtGui.QLineEdit(self.groupBox)
        self.password2.setEchoMode(QtGui.QLineEdit.Password)
        self.password2.setObjectName(_fromUtf8("password2"))
        self.gridlayout.addWidget(self.password2, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridlayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.password = QtGui.QLineEdit(self.groupBox)
        self.password.setEchoMode(QtGui.QLineEdit.Password)
        self.password.setObjectName(_fromUtf8("password"))
        self.gridlayout.addWidget(self.password, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridlayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.vboxlayout1.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.inputPage)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout1.setMargin(9)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.userName = QtGui.QLineEdit(self.groupBox_2)
        self.userName.setObjectName(_fromUtf8("userName"))
        self.gridlayout1.addWidget(self.userName, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridlayout1.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridlayout1.addWidget(self.label_5, 0, 0, 1, 2)
        self.vboxlayout1.addWidget(self.groupBox_2)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.createKeyButton = QtGui.QPushButton(self.inputPage)
        self.createKeyButton.setDefault(False)
        self.createKeyButton.setObjectName(_fromUtf8("createKeyButton"))
        self.hboxlayout.addWidget(self.createKeyButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.vboxlayout1.addLayout(self.hboxlayout)
        self.stack.addWidget(self.inputPage)
        self.progressPage = QtGui.QWidget()
        self.progressPage.setObjectName(_fromUtf8("progressPage"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.progressPage)
        self.vboxlayout2.setMargin(9)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.msgLabel = QtGui.QLabel(self.progressPage)
        self.msgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.msgLabel.setObjectName(_fromUtf8("msgLabel"))
        self.vboxlayout2.addWidget(self.msgLabel)
        self.stack.addWidget(self.progressPage)
        self.errorPage = QtGui.QWidget()
        self.errorPage.setObjectName(_fromUtf8("errorPage"))
        self.vboxlayout3 = QtGui.QVBoxLayout(self.errorPage)
        self.vboxlayout3.setMargin(9)
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        self.label_11 = QtGui.QLabel(self.errorPage)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.vboxlayout3.addWidget(self.label_11)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem2)
        self.tryAgainButton = QtGui.QPushButton(self.errorPage)
        self.tryAgainButton.setObjectName(_fromUtf8("tryAgainButton"))
        self.hboxlayout1.addWidget(self.tryAgainButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem3)
        self.vboxlayout3.addLayout(self.hboxlayout1)
        self.stack.addWidget(self.errorPage)
        self.vboxlayout.addWidget(self.stack)

        self.retranslateUi(CreateKeyDialog)
        self.stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CreateKeyDialog)
        CreateKeyDialog.setTabOrder(self.password, self.password2)
        CreateKeyDialog.setTabOrder(self.password2, self.userName)
        CreateKeyDialog.setTabOrder(self.userName, self.createKeyButton)

    def retranslateUi(self, CreateKeyDialog):
        CreateKeyDialog.setWindowTitle(_translate("CreateKeyDialog", "Create Private Key...", None))
        self.label.setText(_translate("CreateKeyDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:MS Shell Dlg 2; font-size:8.25pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">A 2048-bit RSA Key will created.</span></p></body></html>", None))
        self.groupBox.setTitle(_translate("CreateKeyDialog", "Password", None))
        self.label_4.setText(_translate("CreateKeyDialog", "Re-enter Password:", None))
        self.label_2.setText(_translate("CreateKeyDialog", "The password will be used to encrypt your key before storing it on your hard disk.", None))
        self.label_3.setText(_translate("CreateKeyDialog", "Password:", None))
        self.groupBox_2.setTitle(_translate("CreateKeyDialog", "Username", None))
        self.label_6.setText(_translate("CreateKeyDialog", "Username:", None))
        self.label_5.setText(_translate("CreateKeyDialog", "The username you enter will be used only for display purposes, and is NOT A UNIQUE IDENTIFIER.\n"
"Only lowercase alphabets(a-z), digits(0-9) and underscore(\'_\') can be used in your username.", None))
        self.createKeyButton.setText(_translate("CreateKeyDialog", "&Create Key...", None))
        self.msgLabel.setText(_translate("CreateKeyDialog", "Progress Message...", None))
        self.label_11.setText(_translate("CreateKeyDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:MS Shell Dlg 2; font-size:8.25pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600; color:#ff0000;\">Unable to register your Public Key with the Key Server.</span></p><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600; color:#ff0000;\">Please check your internet connection.</p></body></html>", None))
        self.tryAgainButton.setText(_translate("CreateKeyDialog", "Try Again...", None))

import images_rc
