# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sun May 24 16:09:45 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(283, 376)
        icon = QtGui.QIcon()
        icon.addFile(_fromUtf8(":/images/cspace32.png"))
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.vboxlayout = QtGui.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.stack = QtGui.QStackedWidget(self.centralwidget)
        self.stack.setObjectName(_fromUtf8("stack"))
        self.contactsPage = QtGui.QWidget()
        self.contactsPage.setObjectName(_fromUtf8("contactsPage"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.contactsPage)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setSpacing(0)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.contacts = QtGui.QListWidget(self.contactsPage)
        self.contacts.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.contacts.setIconSize(QtCore.QSize(24, 24))
        self.contacts.setResizeMode(QtGui.QListView.Adjust)
        self.contacts.setObjectName(_fromUtf8("contacts"))
        item = QtGui.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addFile(_fromUtf8(":/images/user_online.png"))
        item.setIcon(icon1)
        self.contacts.addItem(item)
        item = QtGui.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addFile(_fromUtf8(":/images/user_offline.png"))
        item.setIcon(icon2)
        self.contacts.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon1)
        self.contacts.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon2)
        self.contacts.addItem(item)
        self.vboxlayout1.addWidget(self.contacts)
        self.stack.addWidget(self.contactsPage)
        self.offlinePage = QtGui.QWidget()
        self.offlinePage.setObjectName(_fromUtf8("offlinePage"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.offlinePage)
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setSpacing(0)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.goOnlineButton = QtGui.QPushButton(self.offlinePage)
        self.goOnlineButton.setObjectName(_fromUtf8("goOnlineButton"))
        self.hboxlayout.addWidget(self.goOnlineButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.vboxlayout2.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem2)
        self.createKeyButton = QtGui.QPushButton(self.offlinePage)
        self.createKeyButton.setObjectName(_fromUtf8("createKeyButton"))
        self.hboxlayout1.addWidget(self.createKeyButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem3)
        self.vboxlayout2.addLayout(self.hboxlayout1)
        self.stack.addWidget(self.offlinePage)
        self.offlineNoUsersPage = QtGui.QWidget()
        self.offlineNoUsersPage.setObjectName(_fromUtf8("offlineNoUsersPage"))
        self.vboxlayout3 = QtGui.QVBoxLayout(self.offlineNoUsersPage)
        self.vboxlayout3.setMargin(0)
        self.vboxlayout3.setSpacing(0)
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setSpacing(0)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem4)
        self.createKeyButton1 = QtGui.QPushButton(self.offlineNoUsersPage)
        self.createKeyButton1.setObjectName(_fromUtf8("createKeyButton1"))
        self.hboxlayout2.addWidget(self.createKeyButton1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem5)
        self.vboxlayout3.addLayout(self.hboxlayout2)
        self.stack.addWidget(self.offlineNoUsersPage)
        self.connectingPage = QtGui.QWidget()
        self.connectingPage.setObjectName(_fromUtf8("connectingPage"))
        self.vboxlayout4 = QtGui.QVBoxLayout(self.connectingPage)
        self.vboxlayout4.setMargin(9)
        self.vboxlayout4.setSpacing(6)
        self.vboxlayout4.setObjectName(_fromUtf8("vboxlayout4"))
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout4.addItem(spacerItem6)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setMargin(0)
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem7)
        self.vboxlayout5 = QtGui.QVBoxLayout()
        self.vboxlayout5.setMargin(0)
        self.vboxlayout5.setSpacing(6)
        self.vboxlayout5.setObjectName(_fromUtf8("vboxlayout5"))
        self.connectStatus = QtGui.QLabel(self.connectingPage)
        self.connectStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.connectStatus.setObjectName(_fromUtf8("connectStatus"))
        self.vboxlayout5.addWidget(self.connectStatus)
        self.connectCancelButton = QtGui.QPushButton(self.connectingPage)
        self.connectCancelButton.setObjectName(_fromUtf8("connectCancelButton"))
        self.vboxlayout5.addWidget(self.connectCancelButton)
        self.hboxlayout3.addLayout(self.vboxlayout5)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem8)
        self.vboxlayout4.addLayout(self.hboxlayout3)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout4.addItem(spacerItem9)
        self.stack.addWidget(self.connectingPage)
        self.vboxlayout.addWidget(self.stack)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 283, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menuC_ontacts = QtGui.QMenu(self.menubar)
        self.menuC_ontacts.setObjectName(_fromUtf8("menuC_ontacts"))
        self.menu_CSpace = QtGui.QMenu(self.menubar)
        self.menu_CSpace.setObjectName(_fromUtf8("menu_CSpace"))
        self.menuO_ptions = QtGui.QMenu(self.menubar)
        self.menuO_ptions.setObjectName(_fromUtf8("menuO_ptions"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(4, self.toolBar)
        self.actionCreateKey = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addFile(_fromUtf8(":/images/register32.png"))
        self.actionCreateKey.setIcon(icon3)
        self.actionCreateKey.setObjectName(_fromUtf8("actionCreateKey"))
        self.actionGoOnline = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addFile(_fromUtf8(":/images/connect32.png"))
        self.actionGoOnline.setIcon(icon4)
        self.actionGoOnline.setObjectName(_fromUtf8("actionGoOnline"))
        self.actionGoOffline = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addFile(_fromUtf8(":/images/disconnect32.png"))
        self.actionGoOffline.setIcon(icon5)
        self.actionGoOffline.setObjectName(_fromUtf8("actionGoOffline"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addFile(_fromUtf8(":/images/exit32.png"))
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAddContact = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addFile(_fromUtf8(":/images/user_add32.png"))
        self.actionAddContact.setIcon(icon7)
        self.actionAddContact.setObjectName(_fromUtf8("actionAddContact"))
        self.actionRefreshStatus = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addFile(_fromUtf8(":/images/refresh32.png"))
        self.actionRefreshStatus.setIcon(icon8)
        self.actionRefreshStatus.setObjectName(_fromUtf8("actionRefreshStatus"))
        self.actionCheckStatus = QtGui.QAction(MainWindow)
        self.actionCheckStatus.setIcon(icon8)
        self.actionCheckStatus.setObjectName(_fromUtf8("actionCheckStatus"))
        self.actionContactInfo = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addFile(_fromUtf8(":/images/contact_info32.png"))
        self.actionContactInfo.setIcon(icon9)
        self.actionContactInfo.setObjectName(_fromUtf8("actionContactInfo"))
        self.actionRemoveContact = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addFile(_fromUtf8(":/images/user_remove32.png"))
        self.actionRemoveContact.setIcon(icon10)
        self.actionRemoveContact.setObjectName(_fromUtf8("actionRemoveContact"))
        self.actionEditPermissions = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addFile(_fromUtf8(":/images/edit_permissions32.png"))
        self.actionEditPermissions.setIcon(icon11)
        self.actionEditPermissions.setObjectName(_fromUtf8("actionEditPermissions"))
        self.actionAboutCSpace = QtGui.QAction(MainWindow)
        self.actionAboutCSpace.setIcon(icon)
        self.actionAboutCSpace.setObjectName(_fromUtf8("actionAboutCSpace"))
        self.actionKeyInfo = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addFile(_fromUtf8(":/images/key_info32.png"))
        self.actionKeyInfo.setIcon(icon12)
        self.actionKeyInfo.setObjectName(_fromUtf8("actionKeyInfo"))
        self.menu_Help.addAction(self.actionAboutCSpace)
        self.menuC_ontacts.addAction(self.actionAddContact)
        self.menuC_ontacts.addAction(self.actionRefreshStatus)
        self.menu_CSpace.addAction(self.actionGoOnline)
        self.menu_CSpace.addAction(self.actionGoOffline)
        self.menu_CSpace.addAction(self.actionKeyInfo)
        self.menu_CSpace.addSeparator()
        self.menu_CSpace.addAction(self.actionCreateKey)
        self.menu_CSpace.addSeparator()
        self.menu_CSpace.addAction(self.actionExit)
        self.menuO_ptions.addAction(self.actionEditPermissions)
        self.menubar.addAction(self.menu_CSpace.menuAction())
        self.menubar.addAction(self.menuC_ontacts.menuAction())
        self.menubar.addAction(self.menuO_ptions.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.actionGoOnline)
        self.toolBar.addAction(self.actionCreateKey)
        self.toolBar.addAction(self.actionGoOffline)
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAddContact)
        self.toolBar.addAction(self.actionRefreshStatus)

        self.retranslateUi(MainWindow)
        self.stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CSpace", None))
        __sortingEnabled = self.contacts.isSortingEnabled()
        self.contacts.setSortingEnabled(False)
        item = self.contacts.item(0)
        item.setText(_translate("MainWindow", "Item 1", None))
        item = self.contacts.item(1)
        item.setText(_translate("MainWindow", "Item 2", None))
        item = self.contacts.item(2)
        item.setText(_translate("MainWindow", "Item 3", None))
        item = self.contacts.item(3)
        item.setText(_translate("MainWindow", "Item 4", None))
        self.contacts.setSortingEnabled(__sortingEnabled)
        self.goOnlineButton.setText(_translate("MainWindow", "Go Online...", None))
        self.createKeyButton.setText(_translate("MainWindow", "Create Private Key...", None))
        self.createKeyButton1.setText(_translate("MainWindow", "Create Private Key...", None))
        self.connectStatus.setText(_translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:MS Shell Dlg; font-size:8.25pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><span style=\" font-weight:600;\">Connect failed.</span></p><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\">Reconnecting in 30 second(s)...</p></body></html>", None))
        self.connectCancelButton.setText(_translate("MainWindow", "Cancel", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.menuC_ontacts.setTitle(_translate("MainWindow", "C&ontacts", None))
        self.menu_CSpace.setTitle(_translate("MainWindow", "&CSpace", None))
        self.menuO_ptions.setTitle(_translate("MainWindow", "O&ptions", None))
        self.actionCreateKey.setText(_translate("MainWindow", "&Create Private Key...", None))
        self.actionCreateKey.setIconText(_translate("MainWindow", "Create Private Key", None))
        self.actionCreateKey.setToolTip(_translate("MainWindow", "Create Private Key", None))
        self.actionGoOnline.setText(_translate("MainWindow", "&Go Online...", None))
        self.actionGoOffline.setText(_translate("MainWindow", "Go &Offline", None))
        self.actionExit.setText(_translate("MainWindow", "E&xit", None))
        self.actionAddContact.setText(_translate("MainWindow", "&Add Contact...", None))
        self.actionAddContact.setIconText(_translate("MainWindow", "Add Contact", None))
        self.actionAddContact.setToolTip(_translate("MainWindow", "Add Contact", None))
        self.actionRefreshStatus.setText(_translate("MainWindow", "Refresh &Status", None))
        self.actionCheckStatus.setText(_translate("MainWindow", "&Check Status", None))
        self.actionContactInfo.setText(_translate("MainWindow", "Contact &Information...", None))
        self.actionRemoveContact.setText(_translate("MainWindow", "Remove Contact", None))
        self.actionEditPermissions.setText(_translate("MainWindow", "&Edit Permissions...", None))
        self.actionAboutCSpace.setText(_translate("MainWindow", "&About CSpace...", None))
        self.actionKeyInfo.setText(_translate("MainWindow", "Key Information...", None))

import images_rc
